<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props">
  </Import>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>NextWave.Erp.GraphQL.Tests</AssemblyName>
    <PackageId>NextWave.Erp.GraphQL.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NextWave.Erp.GraphQL\NextWave.Erp.GraphQL.csproj" />
    <ProjectReference Include="..\NextWave.Erp.Test.Base\NextWave.Erp.Test.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
  </ItemGroup>
</Project>
