<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props">
  </Import>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>NextWave.Erp.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>NextWave.Erp.Migrator</PackageId>
    <UserSecretsId>NextWave-Erp-894FDFC1-6482-4A56-926A-3C46C9FE0329</UserSecretsId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <LangVersion>latest</LangVersion>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="10.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NextWave.Erp.EntityFrameworkCore\NextWave.Erp.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
