import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';
@NgModule({
    providers: [
       ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.TrailBalanceReportServiceProxy,
        ApiServiceProxies.BalanceSheetReportServiceProxy,
        ApiServiceProxies.ProfitAndLossReportServiceProxy,
        ApiServiceProxies.CashFlowReportServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.PaymentMastersServiceProxy,
        ApiServiceProxies.ReceiptMastersServiceProxy,
        ApiServiceProxies.JournalMastersServiceProxy,
        ApiServiceProxies.ContraMastersServiceProxy,
        ApiServiceProxies.PDCPayablesServiceProxy,
        ApiServiceProxies.PDCReceivablesServiceProxy,
        ApiServiceProxies.PDCClearancesServiceProxy,

        ApiServiceProxies.AccountGroupReportServiceProxy,
        ApiServiceProxies.AccountLedgerReportServiceProxy,
        ApiServiceProxies.StockManagementServiceProxy,
        ApiServiceProxies.StockReportServiceProxy,
        ApiServiceProxies.ProductProfitReportServiceProxy,
        ApiServiceProxies.MergeLedgerServiceProxy,
        ApiServiceProxies.ProductMergeServiceProxy,
        ApiServiceProxies.PurchaseMasterReportServiceProxy,
        ApiServiceProxies.PurchaseReturnReportServiceProxy,
        ApiServiceProxies.TaxableCustomerServiceProxy,
        ApiServiceProxies.MonthlyPurchaseReportServiceProxy,
        ApiServiceProxies.SalesMasterReportServiceProxy,
        ApiServiceProxies.SalesReturnReportServiceProxy,
        ApiServiceProxies.MaterialSalesReportServiceProxy,
        ApiServiceProxies.MonthlySalesReportServiceProxy,

        ApiServiceProxies.VATSummaryReportServiceProxy,
        ApiServiceProxies.TaxReportServiceProxy,
        ApiServiceProxies.DashboardReportDataServiceProxy,
        ApiServiceProxies.ReportingServiceProxy,

        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,
        ApiServiceProxies.EntityChangeServiceProxy,
        ApiServiceProxies.AccountGroupsServiceProxy,
        ApiServiceProxies.AccountLedgersServiceProxy,
        ApiServiceProxies.FinancialYearsServiceProxy,
        ApiServiceProxies.TaxesServiceProxy,
        ApiServiceProxies.VoucherTypesServiceProxy,
        ApiServiceProxies.UnitsServiceProxy,
        ApiServiceProxies.ProductGroupsServiceProxy,
        ApiServiceProxies.ProductServiceProxy,
        ApiServiceProxies.PurchaseOrderMastersServiceProxy,
        ApiServiceProxies.PurchaseMastersServiceProxy,
        ApiServiceProxies.PurchaseReturnsServiceProxy,
        ApiServiceProxies.SalesMastersServiceProxy,
        ApiServiceProxies.SalesReturnMastersServiceProxy,
        ApiServiceProxies.RestaurantSetupServiceProxy,
        ApiServiceProxies.RestaurantMenuServiceProxy,
        ApiServiceProxies.RestaurantOrderServiceProxy,
        ApiServiceProxies.RestaurantBillingServiceProxy,
        ApiServiceProxies.RestaurantChannelServiceProxy,
        ApiServiceProxies.RestaurantInventoryServiceProxy,
        ApiServiceProxies.RestaurantKdsServiceProxy,
        ApiServiceProxies.RestaurantSyncServiceProxy,
        ApiServiceProxies.RestaurantReportsServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
    ],
})
export class ServiceProxyModule {}
