<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props">
  </Import>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <RootNamespace>NextWave.Erp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL" Version="8.8.4" />
    <PackageReference Include="GraphQL.MicrosoftDI" Version="8.8.4" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.8.4" />
    <PackageReference Include="GraphQL.DataLoader" Version="8.8.4" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="8.3.3" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="8.3.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NextWave.Erp.Application.Shared\NextWave.Erp.Application.Shared.csproj" />
    <ProjectReference Include="..\NextWave.Erp.Core\NextWave.Erp.Core.csproj" />
  </ItemGroup>
</Project>
